baseURL: /
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
copyright: sibiraj-s
disableKinds:
  - taxonomyTerm
languages:
  en:
    languageName: English
    languageCode: en
    contentDir: content/english
    title: Multilingual Mode
    weight: 1
    menu:
      main:
        - name: Home
          url: .
          identifier: home
          weight: 1
        - name: About
          url: about/
          identifier: about
          weight: 2
        - name: Contact
          url: contact/
          identifier: contact
          weight: 3
  es:
    languageName: Spanish
    languageCode: es
    contentDir: content/spanish
    title: Modo multilingüe
    weight: 2
    menu:
      main:
        - name: Casa
          url: .
          identifier: home
          weight: 1
        - name: Acerca de
          url: about/
          identifier: about
          weight: 2
        - name: Contacto
          url: contact/
          identifier: contact
          weight: 3
